apiVersion: v1
kind: Service
metadata:
  name: poetry-test-svc-cip
spec:
  selector:
    app: poetry-test
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poetry-test
spec:
  selector:
    matchLabels:
      app: poetry-test
  replicas: 4
  template:
    metadata:
      labels:
        app: poetry-test
    spec:
      securityContext:
        runAsNonRoot: true  # Pod must not run as root
        runAsUser: 1000     # Run pod as non-root UID 1001
      containers:
      - name: poetry-test
        image: poetry-test:latest
        imagePullPolicy: Always
        ports:
        - containerPort:  8000
          protocol: TCP
        securityContext:
          readOnlyRootFilesystem: true # Makes root filesystem read-only
          allowPrivilegeEscalation: false  # No privilege escalation
          privileged: false   # Ensure it doesn't run in privileged mode
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}

